# Hypothesis Testing(grubbs test)

In [3]:
import numpy as np
import scipy.stats as stats
x = np.array([12,13,14,19,21,23])
y = np.array([12,13,14,19,21,23,45])
def grubbs_test(x):
    n = len(x)
    mean_x = np.mean(x)
    sd_x = np.std(x)
    numerator = max(abs(x-mean_x))
    g_calculated = numerator/sd_x
    print("Grubbs Calculated Value:",g_calculated)
    t_value = stats.t.ppf(1 - 0.05 / (2 * n), n - 2)
    g_critical = ((n - 1) * np.sqrt(np.square(t_value))) / (np.sqrt(n) * np.sqrt(n - 2 + np.square(t_value)))
    print("Grubbs Critical Value:",g_critical)
    if g_critical > g_calculated:
        print("From grubbs_test we observe that calculated value is lesser than critical value, Accept null hypothesis and conclude that there is no outliers\n")
    else:
        print("From grubbs_test we observe that calculated value is greater than critical value, Reject null hypothesis and conclude that there is an outliers\n")
grubbs_test(x)
grubbs_test(y)

Grubbs Calculated Value: 1.4274928542926593
Grubbs Critical Value: 1.8871451177787137
From grubbs_test we observe that calculated value is lesser than critical value, Accept null hypothesis and conclude that there is no outliers

Grubbs Calculated Value: 2.2765147221587774
Grubbs Critical Value: 2.019968507680656
From grubbs_test we observe that calculated value is greater than critical value, Reject null hypothesis and conclude that there is an outliers



# Z-Score

In [19]:
import numpy as np

# Sample data
x = np.array([12, 13, 14, 19, 21, 23])
y = np.array([12, 13, 14, 19, 21, 23, 45000])

# Z-Score threshold for detecting outliers
threshold = 2  

def z_score_outliers(data):
    mean_data = np.mean(data)
    std_dev = np.std(data)
    z_scores = np.abs((data - mean_data) / std_dev)  # Calculate Z-Scores
    print("Z-Scores:", z_scores)
    
    # Find outliers based on the threshold
    outliers = data[z_scores > threshold]
    if len(outliers) > 0:
        print(f"Outliers detected: {outliers}")
    else:
        print("No outliers detected")    
    return outliers

# Run Z-Score outlier detection on the sample data
print("Checking for outliers in dataset x:")
z_score_outliers(x)
print("\nChecking for outliers in dataset y:")
z_score_outliers(y)

Checking for outliers in dataset x:
Z-Scores: [1.18957738 0.9516619  0.71374643 0.47583095 0.9516619  1.42749285]
No outliers detected

Checking for outliers in dataset y:
Z-Scores: [0.40856592 0.4085024  0.40843887 0.40812122 0.40799416 0.4078671
 2.44948967]
Outliers detected: [45000]


array([45000])

# IQR

In [22]:
import numpy as np

# Sample data
x = np.array([12, 13, 14, 19, 21, 23])
y = np.array([12, 13, 14, 19, 21, 23, 100, 45000])

def iqr_outliers(data):
    # Calculate Q1, Q3, and IQR
    q1 = np.percentile(data, 25)
    q3 = np.percentile(data, 75)
    iqr = q3 - q1
    
    # Define outlier bounds
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    
    # Identify outliers
    outliers = data[(data < lower_bound) | (data > upper_bound)]
    print("IQR Outliers:", outliers if len(outliers) > 0 else "No outliers detected")
    return outliers

# Run IQR outlier detection on the sample data
print("Checking for outliers in dataset x:")
iqr_outliers(x)
print("\nChecking for outliers in dataset y:")
iqr_outliers(y)


Checking for outliers in dataset x:
IQR Outliers: No outliers detected

Checking for outliers in dataset y:
IQR Outliers: [  100 45000]


array([  100, 45000])

# DBSCAN

In [25]:
import numpy as np
from sklearn.cluster import DBSCAN

# Sample data
x = np.array([[12], [13], [14], [19], [21], [23]])  # Reshaping data for DBSCAN
y = np.array([[12], [13], [14], [19], [21], [23], [100], [45000]])

def dbscan_outliers(data, eps=3, min_samples=2):
    # Initialize DBSCAN model
    db = DBSCAN(eps=eps, min_samples=min_samples)
    
    # Fit the model and get labels (-1 represents an outlier)
    labels = db.fit_predict(data)
    
    # Identify outliers
    outliers = data[labels == -1]
    print("DBSCAN Outliers:", outliers.flatten() if len(outliers) > 0 else "No outliers detected")
    return outliers

# Run DBSCAN outlier detection on the sample data
print("Checking for outliers in dataset x:")
dbscan_outliers(x)
print("\nChecking for outliers in dataset y:")
dbscan_outliers(y)


Checking for outliers in dataset x:
DBSCAN Outliers: No outliers detected

Checking for outliers in dataset y:
DBSCAN Outliers: [  100 45000]


array([[  100],
       [45000]])

# Local Outlier Factor

In [28]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor

# Sample data
x = np.array([[12], [13], [14], [19], [21], [23]])  # Reshaping data for LOF
y = np.array([[12], [13], [14], [19], [21], [23], [100], [45000]])

def lof_outliers(data, n_neighbors=2):
    # Initialize LOF model
    lof = LocalOutlierFactor(n_neighbors=n_neighbors, contamination="auto")
    
    # Fit the model and predict outliers (-1 indicates an outlier)
    labels = lof.fit_predict(data)
    
    # Identify outliers
    outliers = data[labels == -1]
    print("LOF Outliers:", outliers.flatten() if len(outliers) > 0 else "No outliers detected")
    return outliers

# Run LOF outlier detection on the sample data
print("Checking for outliers in dataset x:")
lof_outliers(x)
print("\nChecking for outliers in dataset y:")
lof_outliers(y)


Checking for outliers in dataset x:
LOF Outliers: No outliers detected

Checking for outliers in dataset y:
LOF Outliers: [  100 45000]


array([[  100],
       [45000]])

# Isolation Forest

In [32]:
import numpy as np
from sklearn.ensemble import IsolationForest

# Sample data
x = np.array([[12], [13], [14], [19], [21], [23]])  # Reshaping data for Isolation Forest
y = np.array([[12], [13], [14], [19], [21], [23], [100], [45000]])

def isolation_forest_outliers(data, contamination=0.1):
    # Initialize Isolation Forest model
    iso_forest = IsolationForest(contamination=contamination, random_state=42)
    
    # Fit the model and predict outliers (-1 represents an outlier)
    labels = iso_forest.fit_predict(data)
    
    # Identify outliers
    outliers = data[labels == -1]
    print("Isolation Forest Outliers:", outliers.flatten() if len(outliers) > 0 else "No outliers detected")
    return outliers

# Run Isolation Forest outlier detection on the sample data
print("Checking for outliers in dataset x:")
isolation_forest_outliers(x)
print("\nChecking for outliers in dataset y:")
isolation_forest_outliers(y)


Checking for outliers in dataset x:
Isolation Forest Outliers: [23]

Checking for outliers in dataset y:
Isolation Forest Outliers: [45000]


array([[45000]])

# Gaussian Mixture Models (GMM)

In [39]:
import numpy as np
from sklearn.mixture import GaussianMixture
import warnings

# Sample data
x = np.array([[12], [13], [14], [19], [21], [23]])  # Reshaping data for GMM
y = np.array([[12], [13], [14], [19], [21], [23], [100])

# Suppress specific warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=UserWarning)

    def gmm_outliers(data, n_components=2, threshold=0.01):
        # Fit GMM to the data
        gmm = GaussianMixture(n_components=n_components)
        gmm.fit(data)
        
        # Calculate log-likelihood of each point under the model
        scores = gmm.score_samples(data)
        
        # Detect outliers based on the threshold
        outliers = data[scores < np.log(threshold)]
        print("GMM Outliers:", outliers.flatten() if len(outliers) > 0 else "No outliers detected")
        return outliers

    # Run GMM outlier detection on the sample data
    print("Checking for outliers in dataset x:")
    gmm_outliers(x)
    print("\nChecking for outliers in dataset y:")
    gmm_outliers(y)


Checking for outliers in dataset x:
GMM Outliers: No outliers detected

Checking for outliers in dataset y:
GMM Outliers: [100]
